name: CI

on:
  push:
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install extras (may require more time)
          pip install -r requirements-extras.txt
      - name: Start server
        run: |
          nohup uvicorn src.app.main:app --host 127.0.0.1 --port 8000 &
          sleep 2
      - name: Smoke test /health
        run: |
          curl -fsS http://127.0.0.1:8000/health
